# Generated by Django 6.1 on 2026-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisepartner',
            name='franchise_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='franchisepartner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='hr_approval_status',
            field=models.CharField(choices=[('Pending HR Approval', 'Pending HR Approval'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Verified', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='hr_issued_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_biometric_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='franchisepartner',
            name='partner_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='franchisepartner',
            name='region',
            field=models.CharField(default='Germany / EU', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Super Admin', 'Super Admin'), ('General Manager', 'General Manager'), ('Finance', 'Finance'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Academic', 'Academic'), ('Visa', 'Visa'), ('Study Abroad', 'Study Abroad'), ('Jobs', 'Jobs'), ('Front Office', 'Front Office')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin (Global Authority / Kuttan)'), ('CEO', 'Master CEO'), ('General Manager', 'General Manager (Operational Oversight)'), ('Academic HOD', 'Department Head - Education & All Courses'), ('Study Abroad HOD', 'Department Head - Study Abroad Hub'), ('Visa HOD', 'Department Head - Visa & Compliance'), ('Work & Study HOD', 'Department Head - Work and Study Hub'), ('Jobs HOD', 'Department Head - Jobs & Career Hub'), ('HR Manager', 'HR Department Manager'), ('Finance Officer', 'Finance & Accounts Officer'), ('Marketing Exec', 'Marketing Studio Executive'), ('Academic Counselor', 'Front Office Intake & Academic Counselor'), ('Franchise Partner', 'Franchise Partner / Regional Territory Lead'), ('student', 'Student / Candidate Enrollee'), ('employer', 'Corporate Employer / Partner'), ('Tech Admin', 'Tech Admin'), ('Student', 'Student'), ('Partner', 'Partner')], default='student', max_length=50),
        ),
    ]
