# Generated by Django 6.1 on 2026-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_franchisepartner_franchise_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='identifier',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Super Admin', 'Super Admin'), ('General Manager', 'General Manager'), ('Finance', 'Finance'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Academic', 'Academic'), ('Visa', 'Visa'), ('Study Abroad', 'Study Abroad'), ('Jobs', 'Jobs'), ('Front Office', 'Front Office')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin (Global Authority / Kuttan)'), ('CEO', 'Master CEO'), ('General Manager', 'General Manager (Operational Oversight)'), ('Academic HOD', 'Department Head - Education & All Courses'), ('Study Abroad HOD', 'Department Head - Study Abroad Hub'), ('Visa HOD', 'Department Head - Visa & Compliance'), ('Work & Study HOD', 'Department Head - Work and Study Hub'), ('Jobs HOD', 'Department Head - Jobs & Career Hub'), ('HR Manager', 'HR Department Manager'), ('Finance Officer', 'Finance & Accounts Officer'), ('Marketing Exec', 'Marketing Studio Executive'), ('Academic Counselor', 'Front Office Intake & Academic Counselor'), ('Franchise Partner', 'Franchise Partner / Regional Territory Lead'), ('student', 'Student / Candidate Enrollee'), ('employer', 'Corporate Employer / Partner'), ('Tech Admin', 'Tech Admin'), ('Student', 'Student'), ('Partner', 'Partner')], db_index=True, default='student', max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='Application_timesta_5400fb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['department', '-timestamp'], name='Application_departm_153396_idx'),
        ),
    ]
