# Generated by Django 6.1 on 2026-09-11 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStudyPackage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('work-in-india', 'Work & Study in India'), ('work-in-abroad', 'Work & Study in Abroad'), ('german-projects', 'German Onboarding Projects'), ('reward-study-platform', 'Reward & Study Platform')], default='work-in-india', max_length=64)),
                ('category_label', models.CharField(default='Work & Study in India', max_length=128)),
                ('title', models.CharField(help_text='e.g. Office Admin & Accounts, Software Engineer', max_length=255)),
                ('badge', models.CharField(default='Operations', help_text='e.g. Operations, Tech & AI, Global Logistics', max_length=64)),
                ('stipend', models.CharField(default='₹15,000 - ₹25,000 / mo', max_length=128)),
                ('training_duration', models.CharField(default='6 Months Initial Training Session', max_length=128)),
                ('internship_duration', models.CharField(default='6 Months Corporate Pilot', max_length=128)),
                ('certification', models.CharField(default='1-Year Verified Corporate Certificate', max_length=255)),
                ('action_text', models.CharField(default='Apply Now', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('terms_and_conditions', models.TextField(blank=True, default='', help_text='Detailed modal policy and candidate guidelines')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Active', max_length=32)),
                ('promoted_to_marketing', models.BooleanField(default=False)),
                ('marketing_campaign_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work & Study Package',
                'verbose_name_plural': 'Work & Study Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkStudyCandidate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('selected_stream', models.CharField(blank=True, default='', max_length=128)),
                ('stage', models.CharField(choices=[('Intake Assessment', 'Intake Assessment'), ('AI & Skill Training', 'AI & Skill Training'), ('Active Internship / Pilot', 'Active Internship / Pilot'), ('German Sponsor Match', 'German Sponsor Match'), ('Graduated & Relocated', 'Graduated & Relocated')], default='Intake Assessment', max_length=64)),
                ('stipend_status', models.CharField(default='Active', max_length=32)),
                ('current_stipend', models.CharField(default='₹18,000 / mo', max_length=64)),
                ('progress_pct', models.PositiveIntegerField(default=10)),
                ('mentor_hod', models.CharField(default='Vikramaditya Roy (Head of IT)', max_length=128)),
                ('attendance_pct', models.PositiveIntegerField(default=95)),
                ('performance_rating', models.FloatField(default=4.8)),
                ('corporate_project', models.CharField(default='ILA Multi-Channel CRM & Automation', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='work_study.workstudypackage')),
            ],
            options={
                'verbose_name': 'Work & Study Candidate',
                'verbose_name_plural': 'Work & Study Candidates',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkStudyRoleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_milestone', models.BooleanField(default=False, help_text='True for top 3 mandatory training milestone highlights')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='work_study.workstudypackage')),
            ],
            options={
                'verbose_name': 'Package Feature / Role',
                'verbose_name_plural': 'Package Features & Roles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkStudyStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='work_study.workstudypackage')),
            ],
            options={
                'verbose_name': 'Selectable Course Stream',
                'verbose_name_plural': 'Selectable Course Streams',
            },
        ),
    ]
