# Generated by Django 6.1 on 2026-09-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('package_option', models.CharField(choices=[('standard', 'The Co-Founder Syndicate'), ('partnership', 'The Enterprise Alliance (Partner)'), ('candidate', 'The Enterprise Alliance (Candidate)'), ('remote', 'ILA Ent Pilot Mode (Remote)')], default='standard', max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('contacted', 'Contacted'), ('archived', 'Archived')], default='received', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('model_used', models.CharField(default='gemini', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('share_capital', models.CharField(default='€25,000', max_length=100)),
                ('setup_fee', models.CharField(max_length=100)),
                ('ownership', models.CharField(max_length=150)),
                ('monthly_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.JSONField(default=list, help_text='List of feature bullet points')),
                ('highlight', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
