# Generated by Django 6.1 on 2026-09-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessStudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessagelog',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='chatmessagelog',
            name='model_used',
            field=models.CharField(default='gemini-1.5-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmessagelog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='default-session', help_text='Frontend session UUID', max_length=120),
        ),
    ]
