# Generated by Django 6.1 on 2026-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessStudio', '0002_alter_chatmessagelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagelog',
            name='model_used',
            field=models.CharField(default='gemini-2.5-flash', max_length=100),
        ),
    ]
