# Generated by Django 6.1 on 2026-09-08 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportExport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('escrow_fee_percent', models.DecimalField(decimal_places=2, default=1.25, max_digits=5)),
                ('sanctions_auto_screen', models.BooleanField(default=True)),
                ('multi_sig_quorum', models.CharField(default='3 of 4', max_length=50)),
                ('oracle_inspection_required', models.BooleanField(default=True)),
                ('auto_disburse_payroll', models.BooleanField(default=True)),
                ('ais_telemetry_tracking', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform Governance Settings',
                'verbose_name_plural': 'Platform Governance Settings',
            },
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='assigned_director',
            field=models.CharField(blank=True, default='Arthur Sterling (CEO Office)', max_length=150),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='counter_party',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='current_stage',
            field=models.CharField(blank=True, default='Initial Due Diligence Review', max_length=255),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='deal_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='lead_party',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='next_milestone',
            field=models.CharField(blank=True, default='Customs Inter-Agency MoU', max_length=255),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='partnership_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='priority',
            field=models.CharField(blank=True, default='High', max_length=50),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='sla_compliance',
            field=models.CharField(blank=True, default='99.1%', max_length=50),
        ),
        migrations.AddField(
            model_name='strategictieup',
            name='target_annual_value',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategictieup',
            name='country',
            field=models.CharField(blank=True, default='Global', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategictieup',
            name='partner_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='strategictieup',
            name='partner_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategictieup',
            name='scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='strategictieup',
            name='signed_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
