# Generated by Django 6.1 on 2026-09-06 18:22

import Applications.ILA_WEB.Academics.academics_models
import Applications.ILA_WEB.Finance.finance_models
import Applications.ILA_WEB.FrontOffice.frontoffice_models
import Applications.ILA_WEB.HRMS.hrms_models
import Applications.ILA_WEB.Rewards.rewards_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionItem',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Finance.finance_models.generate_comm_id, max_length=50, primary_key=True, serialize=False)),
                ('consultant_name', models.CharField(max_length=255)),
                ('referral_code', models.CharField(db_index=True, max_length=50)),
                ('lead_name', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FundPool',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Finance.finance_models.generate_fund_id, max_length=50, primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Operations', 'Operations'), ('Marketing', 'Marketing'), ('Reserve', 'Reserve'), ('Emergency', 'Emergency')], default='Operations', max_length=50)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCategory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRCandidate',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.HRMS.hrms_models.generate_cand_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('Hiring & Interview', 'Hiring & Interview'), ('Pending Department Approval', 'Pending Department Approval'), ('Onboarding & Payroll', 'Onboarding & Payroll'), ('Training & ID Generation', 'Training & ID Generation'), ('Completed', 'Completed')], default='Hiring & Interview', max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('expected_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('offered_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('character_analysis', models.TextField(blank=True)),
                ('resume_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalyzingStrategy',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_metric', models.CharField(max_length=100)),
                ('threshold', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('adaptation_action', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeachingStrategy',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('pacing_model', models.CharField(blank=True, max_length=100)),
                ('target_learner', models.CharField(blank=True, max_length=255)),
                ('default_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TierRule',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tier_name', models.CharField(max_length=50)),
                ('min_referrals', models.IntegerField(default=0)),
                ('bonus_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('base_reward', models.DecimalField(decimal_places=2, default=50.0, max_digits=12)),
                ('color', models.CharField(default='#CD7F32', max_length=50)),
            ],
            options={
                'ordering': ['min_referrals'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=255)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.HRMS.hrms_models.generate_req_id, max_length=50, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('New Staff', 'New Staff'), ('New Course', 'New Course'), ('Data Edit', 'Data Edit'), ('Deletion', 'Deletion'), ('General', 'General')], default='General', max_length=50)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseTask',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.HRMS.hrms_models.generate_task_id, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assigned_to_dept', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Success', 'Success'), ('Negative', 'Negative')], default='Pending', max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Finance.finance_models.generate_led_id, max_length=50, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalCourse',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('top_title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('sub_category_name', models.CharField(blank=True, max_length=255)),
                ('show_in_sub_nav', models.BooleanField(default=True)),
                ('display_position', models.IntegerField(default=0)),
                ('view_type', models.CharField(choices=[('Main View', 'Main View'), ('Blocks View', 'Blocks View'), ('Both', 'Both')], default='Both', max_length=50)),
                ('library_type', models.CharField(choices=[('TUTOR', 'TUTOR'), ('AI', 'AI')], default='TUTOR', max_length=50)),
                ('staff_assigned', models.CharField(blank=True, max_length=255, null=True)),
                ('chapters_count', models.IntegerField(default=0)),
                ('duration', models.CharField(default='3 Months', max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('course_structure', models.TextField(blank=True)),
                ('ai_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='ILA_WEB.globalcategory')),
            ],
            options={
                'ordering': ['display_position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('chapters', 'chapters'), ('images', 'images'), ('video', 'video'), ('promo', 'promo')], default='chapters', max_length=50)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='ILA_WEB.globalcourse')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPath',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('methods', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='ILA_WEB.globalcourse')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalBatch',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Academics.academics_models.generate_batch_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('timings', models.JSONField(blank=True, default=list)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ILA_WEB.globalcourse')),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='ILA_WEB.globalpath')),
            ],
        ),
        migrations.CreateModel(
            name='ClassScheduleSession',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Academics.academics_models.generate_session_id, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('instructor', models.CharField(max_length=255)),
                ('time_slot', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled')], default='Upcoming', max_length=50)),
                ('room', models.CharField(default='Studio A', max_length=100)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=255)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_sessions', to='ILA_WEB.globalbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sessions', to='ILA_WEB.globalcourse')),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_sessions', to='ILA_WEB.globalpath')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSubCategory',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Academics.academics_models.generate_subcategory_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ILA_WEB.globalcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.FrontOffice.frontoffice_models.generate_inquiry_id, max_length=50, primary_key=True, serialize=False)),
                ('token_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lead_type', models.CharField(choices=[('Walk-in', 'Walk-in'), ('Online', 'Online'), ('Referral', 'Referral'), ('Phone', 'Phone')], default='Walk-in', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(default='Education', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('path_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slot', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Link Sent', 'Link Sent'), ('Refunded', 'Refunded')], default='Pending', max_length=50)),
                ('class_link', models.URLField(blank=True, null=True)),
                ('source', models.CharField(default='Front-Desk Reception', max_length=255)),
                ('crm_status', models.CharField(choices=[('New Lead', 'New Lead'), ('In Progress', 'In Progress'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='New Lead', max_length=50)),
                ('pipeline_stage', models.CharField(choices=[('Intake', 'Intake'), ('Assessment', 'Assessment'), ('Documentation', 'Documentation'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Intake', max_length=50)),
                ('visa_stage', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Profile Assessment', 'Profile Assessment'), ('APS Certificate', 'APS Certificate'), ('Blocked Account', 'Blocked Account'), ('Embassy Appointment', 'Embassy Appointment'), ('Visa Approved', 'Visa Approved'), ('Visa Rejected', 'Visa Rejected')], default='Not Applicable', max_length=50)),
                ('intake_notes', models.TextField(blank=True, null=True)),
                ('ai_score', models.IntegerField(default=0)),
                ('ai_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_action_plan', models.JSONField(blank=True, default=dict)),
                ('visitor_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('accompanied_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id_proof_verified', models.BooleanField(default=False)),
                ('check_in_time', models.CharField(blank=True, max_length=50, null=True)),
                ('receptionist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('follow_up_status', models.CharField(choices=[('Due Today', 'Due Today'), ('Overdue', 'Overdue'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.FrontOffice.frontoffice_models.generate_followup_id, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('Phone Call', 'Phone Call'), ('WhatsApp', 'WhatsApp'), ('In-Person', 'In-Person'), ('Email', 'Email')], default='Phone Call', max_length=50)),
                ('notes', models.TextField()),
                ('outcome', models.CharField(choices=[('Interested - Callback', 'Interested - Callback'), ('Docs Pending', 'Docs Pending'), ('Fee Paid', 'Fee Paid'), ('Not Interested', 'Not Interested'), ('Appointment Booked', 'Appointment Booked')], default='Interested - Callback', max_length=50)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_history', to='ILA_WEB.inquiry')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Rewards.rewards_models.generate_ref_id, max_length=50, primary_key=True, serialize=False)),
                ('referrer_name', models.CharField(max_length=255)),
                ('referrer_email', models.EmailField(max_length=254)),
                ('referrer_role', models.CharField(choices=[('Student', 'Student'), ('Partner', 'Partner'), ('Consultant', 'Consultant'), ('Employee', 'Employee')], default='Student', max_length=50)),
                ('candidate_name', models.CharField(max_length=255)),
                ('vertical', models.CharField(choices=[('Education Hub', 'Education Hub'), ('Study Abroad', 'Study Abroad'), ('Work and Study', 'Work and Study'), ('Visa and Services', 'Visa and Services'), ('Jobs and Career', 'Jobs and Career')], default='Education Hub', max_length=50)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('points_earned', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Approved by Marketing', 'Approved by Marketing'), ('Approved by Accounts', 'Approved by Accounts'), ('Paid Out', 'Paid Out'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.Finance.finance_models.generate_sales_id, max_length=50, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=50)),
                ('flag', models.CharField(choices=[('Pending', 'Pending'), ('On Time', 'On Time'), ('Delayed ⚠️', 'Delayed ⚠️')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='ILA_WEB.inquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('resume_url', models.CharField(blank=True, max_length=500)),
                ('hr_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=50)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.CharField(default=Applications.ILA_WEB.HRMS.hrms_models.generate_att_id, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('check_in_time', models.CharField(blank=True, max_length=50)),
                ('check_out_time', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('On Leave', 'On Leave'), ('Late', 'Late')], default='Present', max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='ILA_WEB.staffprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('In Class', 'In Class'), ('Invited', 'Invited'), ('Absent', 'Absent'), ('Completed', 'Completed')], default='Present', max_length=50)),
                ('attendance_score', models.IntegerField(default=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='ILA_WEB.globalbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='ILA_WEB.globalcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
