# Generated by Django 6.1 on 2026-09-09 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILA_WEB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('attendees', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(default='10:00 AM', max_length=50)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('Meta Ads', 'Meta Ads'), ('Google PPC', 'Google PPC'), ('WhatsApp', 'WhatsApp'), ('Field Visits', 'Field Visits'), ('SEO Organic', 'SEO Organic')], max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('target_geography', models.CharField(default='Pan India', max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Active', max_length=50)),
                ('leads_count', models.IntegerField(default=0)),
                ('conversions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('University', 'Public / Private University'), ('Corporate Employer', 'Corporate Employer / Placement'), ('Hospital / Healthcare', 'Hospital / Healthcare'), ('Vocational School (Ausbildung)', 'Vocational School (Ausbildung)')], max_length=100)),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('target_criteria', models.TextField(help_text='Matching qualifications criteria for Indian student corridor')),
                ('commission_ratio', models.CharField(help_text='Profit/Commission or institutional terms', max_length=150)),
                ('status', models.CharField(choices=[('Target Identified', '1. Target Identified'), ('Outreach Drafted', '2. Outreach Drafted'), ('Proposal Dispatched', '3. Proposal Dispatched'), ('In Discussion', '4. In Discussion'), ('MOU Signed', '5. MOU Signed'), ('Active Tie-up Partner', '6. Active Tie-up Partner')], default='Target Identified', max_length=50)),
                ('synced_departments', models.JSONField(default=list, help_text="e.g. ['Study Abroad', 'HR', 'Finance']")),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaRequirementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=100)),
                ('blocked_funds_amount', models.CharField(help_text='e.g. €11,900 / yr', max_length=100)),
                ('embassy_queue_days', models.CharField(default='15-28 Days', max_length=50)),
                ('primary_authority', models.CharField(max_length=200)),
                ('mandatory_checklists', models.JSONField(default=list)),
                ('last_monitored_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStudyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('track', models.CharField(choices=[('Work While You Learn in India', 'Work While You Learn in India'), ('Part time While You Study Abroad', 'Part time While You Study Abroad'), ('German Project Onboarding Pathway', 'German Project Onboarding Pathway'), ('Junior Consultant Track', 'Rewards Plans & Junior Consultant Track')], max_length=100)),
                ('sub_domain', models.CharField(max_length=150)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('ai_preliminary_interview_link', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_interview_score', models.IntegerField(default=0)),
                ('ai_interview_status', models.CharField(choices=[('Pending AI Link', 'Pending AI Link'), ('Completed', 'Completed'), ('Scheduled for HR Round 2', 'Scheduled for HR Round 2')], default='Pending AI Link', max_length=50)),
                ('ai_interview_transcript', models.TextField(blank=True)),
                ('is_onboarded_to_dept', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attendancelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='enterprisetask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='followuprecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={},
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='enterprisetask',
            name='assigned_staff',
        ),
        migrations.RemoveField(
            model_name='followuprecord',
            name='next_follow_up_date',
        ),
        migrations.RemoveField(
            model_name='followuprecord',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='accompanied_by',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='ai_action_plan',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='ai_path',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='assigned_staff',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='batch_name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='class_link',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='department',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='id_proof_verified',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='intake_notes',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='lead_type',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='path_name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='receptionist_name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='source',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='visa_stage',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='visitor_purpose',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='staff_id',
            field=models.CharField(default='EMP-001', max_length=50),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='staff_name',
            field=models.CharField(default='Staff Member', max_length=255),
        ),
        migrations.AddField(
            model_name='enterprisetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='followuprecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='followuprecord',
            name='staff_name',
            field=models.CharField(default='Staff', max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_staff_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='price',
            field=models.CharField(default='$199', max_length=50),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='type',
            field=models.CharField(choices=[('Walk-in', 'Walk-in'), ('Online', 'Online'), ('Referral', 'Referral'), ('Phone', 'Phone')], default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='visa_processing_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='date',
            field=models.CharField(default='2026-09-09', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='department',
            field=models.CharField(default='Operations', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.CharField(default='Staff', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='check_in_time',
            field=models.CharField(default='09:00 AM', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='date',
            field=models.CharField(default='2026-09-09', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(default='Present', max_length=50),
        ),
        migrations.AlterField(
            model_name='enterprisetask',
            name='assigned_to_dept',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='enterprisetask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enterprisetask',
            name='title',
            field=models.CharField(default='Enterprise Task', max_length=255),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='date',
            field=models.CharField(default='2026-09-09', max_length=50),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='ILA_WEB.inquiry'),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='followuprecord',
            name='outcome',
            field=models.CharField(default='Interested', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('Education', 'Education & All Courses'), ('Study Abroad', 'Study Abroad Hub'), ('Visa', 'Visa and Services Hub'), ('Jobs', 'Job and Career Hub'), ('Work While You Study', 'Work While You Study Track'), ('Rewards', 'Rewards Program & Consultant'), ('General Front Office', 'General Front Office Reception')], default='General Front Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='follow_up_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='follow_up_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='pipeline_stage',
            field=models.CharField(default='Intake', max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='token_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='FieldVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_visited', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('next_action', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FranchisePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(default='Germany / EU', max_length=150)),
                ('franchise_token', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchises_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_id', models.CharField(max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('Junior Consultant', 'Junior Consultant'), ('Senior Executive Consultant', 'Senior Executive Consultant'), ('Global Venture Partner', 'Global Venture Partner')], default='Junior Consultant', max_length=50)),
                ('active_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('monthly_points', models.IntegerField(default=0)),
                ('cash_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('promoted_categories', models.JSONField(default=list, help_text='Categories chosen to promote')),
                ('work_certificate_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('milestone_type', models.CharField(choices=[('Inquiry Generated (10 pts)', 'Inquiry Generated'), ('Successful Enrollment (50 pts)', 'Enrollment Conversion'), ('Monthly Payout Unlock (1000 pts)', 'Monthly Payout')], max_length=50)),
                ('reference_inquiry_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ILA_WEB.rewardprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('target_country', models.CharField(default='Germany', max_length=100)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('services_requested', models.JSONField(default=list)),
                ('status', models.CharField(default='Pending Coordinator Assignment', max_length=50)),
                ('assigned_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TieUpOutreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('generated_proposal_text', models.TextField()),
                ('is_dispatched', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_logs', to='ILA_WEB.partnerinstitution')),
            ],
        ),
    ]
