# Generated by Django 6.1 on 2026-09-09 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILA_WEB', '0002_departmentmeeting_marketingcampaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('topic', models.CharField(default='general', max_length=50)),
                ('model_name', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AI Token Usage Log',
                'verbose_name_plural': 'AI Token Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
