# Generated by Django 6.1 on 2026-09-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILA_WEB', '0003_aitokenusagelog_alter_inquiry_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='ai_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='job_role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Searchable tag list extracted from incoming redirection'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reward_tier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='section_data',
            field=models.JSONField(blank=True, default=dict, help_text='All section-specific form fields (batches, tracks, tiers, etc.)'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_page',
            field=models.CharField(blank=True, help_text="Page from which applicant arrived (e.g., 'VisaPage', 'JobsPage')", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_url',
            field=models.CharField(blank=True, help_text='Full origin URL/hash including query parameters', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='target_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='target_keyword',
            field=models.CharField(blank=True, help_text="Primary keyword/title (e.g., 'Opportunity Card', 'Senior React Dev')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='visa_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='crm_status',
            field=models.CharField(default='New Lead', max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='price',
            field=models.CharField(default='Pending Consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='token_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['category', 'crm_status'], name='ILA_WEB_inq_categor_659834_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['target_keyword'], name='ILA_WEB_inq_target__5ac883_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['email'], name='ILA_WEB_inq_email_f82312_idx'),
        ),
    ]
