# Generated by Django 6.1 on 2026-09-11 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('team', 'Team / Staff'), ('employer', 'Employer'), ('candidate', 'Candidate')], default='student', max_length=50)),
                ('department', models.CharField(blank=True, default='Super Admin', max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=50)),
                ('scope', models.CharField(blank=True, default='all', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
