# Generated by Django 6.1 on 2026-09-11 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationWorkflowRule',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Instant Welcome & Portal Access on Registration', max_length=255)),
                ('trigger_event', models.CharField(choices=[('student_registration', 'Step 1: Student Registration Intake'), ('course_enrollment', 'Step 2: Course Enrolled & Active'), ('payment_reminder', 'Step 3: Fee Payment / Deposit Alert'), ('class_start_24h', 'Step 4: Class 24h Countdown Alert'), ('class_start_1h', 'Step 5: Class 1h Emergency Alert'), ('pending_enrollment_24h', 'Drop-off: Incomplete Intake (24h Recovery Nudge)'), ('incomplete_registration_48h', 'Drop-off: Incomplete Registration (48h Recovery)')], default='student_registration', max_length=64)),
                ('category', models.CharField(choices=[('Welcome & Onboarding', 'Welcome & Onboarding'), ('Class & Schedule Alerts', 'Class & Schedule Alerts'), ('Enrollment Follow-ups', 'Enrollment Follow-ups'), ('Payment & Retention', 'Payment & Retention')], default='Welcome & Onboarding', max_length=64)),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp Gateway'), ('Email', 'Email (SMTP / SendGrid)'), ('SMS', 'SMS Gateway'), ('Multi-Channel', 'Multi-Channel (Omni-channel)')], default='WhatsApp', max_length=32)),
                ('subject', models.CharField(help_text='Notification subject line or email subject', max_length=255)),
                ('message_template', models.TextField(help_text='Supports {{name}}, {{course}}, {{time}}, {{tutor}}, {{portal_link}}')),
                ('is_active', models.BooleanField(default=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='0 for instant dispatch, 15, 60, 1440 mins')),
                ('badge', models.CharField(default='Instant Zero-Latency', max_length=64)),
                ('total_dispatched', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Communication Workflow Rule',
                'verbose_name_plural': 'Communication Workflow Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=128)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('course_or_batch', models.CharField(default='General Track', max_length=255)),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp Gateway'), ('Email', 'Email (SMTP / SendGrid)'), ('SMS', 'SMS Gateway'), ('Multi-Channel', 'Multi-Channel (Omni-channel)')], default='WhatsApp', max_length=32)),
                ('status', models.CharField(default='Delivered', max_length=32)),
                ('message_preview', models.TextField()),
                ('latency_ms', models.PositiveIntegerField(default=350)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communication_engine.communicationworkflowrule')),
            ],
            options={
                'verbose_name': 'Dispatch Log',
                'verbose_name_plural': 'Dispatch Logs',
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
