# Generated by Django 6.1 on 2026-09-11 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_name', models.CharField(blank=True, default='Guest Aspirant', max_length=150)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_phone', models.CharField(blank=True, default='', max_length=50)),
                ('topic', models.CharField(default='general', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active Chatting'), ('resolved', 'Resolved by AI'), ('escalated', 'Escalated to Human Counselor'), ('closed', 'Closed Session')], default='active', max_length=32)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('messages_history', models.JSONField(blank=True, default=list, help_text='Chronological conversation record [{id, role, content, timestamp, topic}]')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual client parameters (e.g. current page, referral, device info)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultant Chat Session',
                'verbose_name_plural': 'Consultant Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantChatMessage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User / Applicant'), ('assistant', 'Ilas AI Consultant')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('topic', models.CharField(default='general', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='communication_engine.consultantchatsession')),
            ],
            options={
                'verbose_name': 'Consultant Chat Message',
                'verbose_name_plural': 'Consultant Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
