# Generated by Django 6.1 on 2026-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Education', 'All Course Hub / Education'), ('Work While You Study', 'Work While You Study Hub'), ('Study Abroad', 'Study Abroad Hub'), ('Jobs', 'Job & Career Hub'), ('Rewards', 'Rewards Plan Hub'), ('Visa', 'Visa & Service Hub')], default='Education', max_length=100)),
                ('inquiry_type', models.CharField(choices=[('Walk-in', 'Walk-in Reception'), ('Online Funnel', 'Online Funnel'), ('WhatsApp Direct', 'WhatsApp Direct'), ('Referral', 'Referral')], default='Walk-in', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('program_of_interest', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('In-Review', 'In-Review'), ('Enrolled', 'Enrolled'), ('Dropped', 'Dropped')], default='New', max_length=50)),
                ('counselor_assigned', models.CharField(default='Front Office Lead', max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_contacted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpAutoTriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Education', max_length=100)),
                ('trigger_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('incomplete_enrollment', 'Incomplete Registration'), ('pending_payment', 'Pending Payment / Stipend Sign-off'), ('document_pending', 'Missing Documents'), ('profile_dropoff', 'Profile Inactivity')], default='incomplete_enrollment', max_length=100)),
                ('channel', models.CharField(choices=[('Both', 'WhatsApp + Email'), ('WhatsApp', 'WhatsApp Only'), ('Email', 'Email Only')], default='Both', max_length=50)),
                ('delay_hours', models.IntegerField(default=2)),
                ('message_template', models.TextField(help_text='Dynamic template with {name} and {program}')),
                ('is_active', models.BooleanField(default=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Education', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('channels', models.JSONField(default=list, help_text="e.g. ['Meta Ads', 'LinkedIn', 'Instagram']")),
                ('target_audience', models.CharField(default='All Aspirants in India & Europe', max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Scheduled', 'Scheduled')], default='Draft', max_length=50)),
                ('scheduled_at', models.DateField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reach_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
            ],
        ),
    ]
