# Generated by Django 6.1 on 2026-09-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinquiry',
            name='ai_action_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='ai_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='category',
            field=models.CharField(blank=True, default='General Front Office', max_length=100),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='course',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='crm_status',
            field=models.CharField(blank=True, default='New Lead', max_length=50),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='doc_status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores arbitrary dynamic key-values from any source page/form (e.g. educationLevel, languageSkills, visaHistory, hasBlockedAccount, workExpYears, preferredSalary, etc.)'),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='form_type',
            field=models.CharField(blank=True, default='visa', help_text='Originating form type (e.g. visa, course, job, earn-learn, walkin)', max_length=100),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='pipeline_stage',
            field=models.CharField(blank=True, default='Intake', max_length=50),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='price',
            field=models.CharField(blank=True, default='Complimentary Intake', max_length=100),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='source',
            field=models.CharField(blank=True, default='Website Unified Intake', max_length=255),
        ),
        migrations.AddField(
            model_name='departmentinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='departmentinquiry',
            name='counselor_assigned',
            field=models.CharField(blank=True, default='Front Office Lead', max_length=150),
        ),
        migrations.AlterField(
            model_name='departmentinquiry',
            name='department',
            field=models.CharField(default='Education', max_length=100),
        ),
        migrations.AlterField(
            model_name='departmentinquiry',
            name='inquiry_type',
            field=models.CharField(blank=True, default='Online Funnel', max_length=50),
        ),
        migrations.AlterField(
            model_name='departmentinquiry',
            name='program_of_interest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='departmentinquiry',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
