import io
import logging

logger = logging.getLogger(__name__)


def build_course_docx(course_data) -> io.BytesIO:
    """
    Generates a professional Word (.docx) document from course metadata and chapters.
    Returns an in-memory BytesIO buffer ready for HTTP streaming or S3 storage.
    """
    try:
        import docx
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.table import WD_TABLE_ALIGNMENT
    except ImportError:
        logger.error("[DocxBuilder] python-docx is not installed.")
        buffer = io.BytesIO()
        buffer.write(b"DOCX Generation requires python-docx package.")
        buffer.seek(0)
        return buffer

    doc = docx.Document()

    # Document Header & Title
    title = course_data.get('title', 'ILA Course Curriculum')
    subtitle = course_data.get('subtitle', '')
    category = course_data.get('category', 'Academic')
    overview = course_data.get('overview', '')
    chapters = course_data.get('chapters', [])

    # Main Title
    title_p = doc.add_paragraph()
    title_run = title_p.add_run(title)
    title_run.font.size = Pt(24)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(30, 41, 59) # Deep Navy / Slate
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    if subtitle:
        sub_p = doc.add_paragraph()
        sub_run = sub_p.add_run(subtitle)
        sub_run.font.size = Pt(14)
        sub_run.font.italic = True
        sub_run.font.color.rgb = RGBColor(100, 116, 139)
        sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()  # Spacing

    # Metadata Callout Box
    meta_table = doc.add_table(rows=2, cols=3)
    meta_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    meta_table.autofit = True

    hdr_cells = meta_table.rows[0].cells
    hdr_cells[0].text = "Category"
    hdr_cells[1].text = "Total Chapters"
    hdr_cells[2].text = "Delivery Mode"

    for c in hdr_cells:
        for p in c.paragraphs:
            for r in p.runs:
                r.font.bold = True
                r.font.size = Pt(10)

    val_cells = meta_table.rows[1].cells
    val_cells[0].text = str(category)
    val_cells[1].text = str(len(chapters) or course_data.get('totalChapters', course_data.get('total_chapters', 0)))
    val_cells[2].text = str(course_data.get('deliveryPath', course_data.get('delivery_path', 'Universal / Online')))

    doc.add_paragraph()  # Spacing

    # Course Overview
    if overview:
        h1 = doc.add_heading("Course Overview & Objectives", level=1)
        h1.paragraph_format.space_before = Pt(14)
        h1.paragraph_format.space_after = Pt(6)
        doc.add_paragraph(overview)

    # Chapters Breakdown
    if chapters:
        h_ch = doc.add_heading("Detailed Chapter Syllabus & Modular Units", level=1)
        h_ch.paragraph_format.space_before = Pt(18)
        h_ch.paragraph_format.space_after = Pt(8)

        for chap in chapters:
            ch_num = chap.get('chapterNumber') or chap.get('chapter_number', '')
            ch_title = chap.get('title', f'Chapter {ch_num}')
            ch_summary = chap.get('summary', '')
            ch_content = chap.get('content', '')
            sub_topics = chap.get('subTopics') or chap.get('sub_topics', [])

            # Chapter Heading
            ch_head = doc.add_heading(f"Chapter {ch_num}: {ch_title}", level=2)
            ch_head.paragraph_format.space_before = Pt(12)
            ch_head.paragraph_format.space_after = Pt(4)

            if ch_summary:
                p_sum = doc.add_paragraph()
                p_sum_run = p_sum.add_run(f"Summary: {ch_summary}")
                p_sum_run.font.italic = True
                p_sum_run.font.color.rgb = RGBColor(71, 85, 105)

            if sub_topics and isinstance(sub_topics, list):
                doc.add_heading("Key Learning Sub-Topics:", level=3)
                for st in sub_topics:
                    st_text = st if isinstance(st, str) else st.get('title', str(st))
                    doc.add_paragraph(f"• {st_text}")

            if ch_content:
                doc.add_paragraph(ch_content)

            doc.add_paragraph()  # Space between chapters

    # Footer notice
    doc.add_page_break()
    foot = doc.add_paragraph("Generated by ILA AI Engine Hub & Course Creator Ecosystem")
    foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if foot.runs:
        foot.runs[0].font.size = Pt(9)
        foot.runs[0].font.color.rgb = RGBColor(148, 163, 184)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
