# Generated by Django 6.1 on 2026-09-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantATSTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_account_id', models.CharField(max_length=150)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=50)),
                ('target_country', models.CharField(default='Germany', max_length=100)),
                ('target_course', models.CharField(max_length=255)),
                ('match_score', models.IntegerField(default=90)),
                ('stage', models.CharField(choices=[('Lead / Intake', 'Lead / Intake'), ('Document Verification', 'Document Verification'), ('University Review', 'University Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Visa Preparation', 'Visa Preparation'), ('Enrolled', 'Enrolled'), ('Closed / Dropped', 'Closed / Dropped')], default='Lead / Intake', max_length=50)),
                ('assigned_consultant', models.CharField(default='Sarah Müller (Senior Admissions Lead)', max_length=200)),
                ('uploaded_documents', models.JSONField(default=list, help_text="List of objects: [{'checklistId', 'docName', 'fileName', 'fileSize', 'uploadedAt', 'verified'}]")),
                ('consultant_notes', models.JSONField(default=list, help_text="List of objects: [{'id', 'author', 'note', 'timestamp', 'nextFollowUpDate'}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('flag', models.CharField(default='🇩🇪', max_length=10)),
                ('visa_type', models.CharField(default='National Student Visa (APS / 16b)', max_length=200)),
                ('currency', models.CharField(default='EUR (€)', max_length=50)),
                ('avg_tuition', models.CharField(default='€0 - €3,000 / yr', max_length=150)),
                ('living_cost', models.CharField(default='€934 / mo (Blocked Account)', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Coming Soon', 'Coming Soon')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('course_track', models.CharField(default='All', max_length=100)),
                ('doc_name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('accepted_formats', models.CharField(default='PDF, JPG, PNG', max_length=100)),
                ('max_size_mb', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=150)),
                ('ranking', models.CharField(default='Top Ranked', max_length=100)),
                ('institution_type', models.CharField(choices=[('Public', 'Public University (€0 Tuition)'), ('University of Applied Sciences', 'University of Applied Sciences (UAS)'), ('Technical University', 'Technical University (TU9)'), ('Private', 'Private University')], default='Public', max_length=100)),
                ('admission_criteria', models.TextField(default='Min 7.0 CGPA, APS Certificate, IELTS 6.5')),
                ('terms', models.JSONField(default=list, help_text='List of admission terms/checklists')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Partnered', 'Partnered'), ('Under Review', 'Under Review')], default='Partnered', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='study_abroad.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryTieUpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(help_text='Unique slug/filter key e.g. public_uni, ausbildung, masters', max_length=100)),
                ('label', models.CharField(help_text='Display label e.g. Ausbildung Dual Study', max_length=150)),
                ('badge', models.CharField(blank=True, default='', help_text='e.g. Free Tuition, High Demand', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieup_categories', to='study_abroad.country')),
            ],
            options={
                'verbose_name_plural': 'Country Tie-Up Categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HybridAILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('ILA_AI', 'ILA AI System'), ('HUMAN_CONSULTANT', 'Human Consultant')], default='ILA_AI', max_length=50)),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ats_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_logs', to='study_abroad.consultantatstask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyAbroadCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('Masters', 'Masters (M.Sc / M.Eng)'), ('Bachelors', 'Bachelors (B.Sc / B.Eng)'), ('Ausbildung', 'Ausbildung (Paid Dual Study)'), ('Diploma', 'Diploma / Certificate')], default='Masters', max_length=50)),
                ('duration', models.CharField(default='2 Years (4 Semesters)', max_length=100)),
                ('language', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Bilingual', 'Bilingual')], default='English', max_length=50)),
                ('tuition_per_year', models.CharField(default='€0 (Semester fee only)', max_length=150)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=7.0, max_digits=4)),
                ('min_ielts', models.DecimalField(decimal_places=1, default=6.5, max_digits=3)),
                ('min_german_level', models.CharField(choices=[('None', 'None'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='None', max_length=20)),
                ('intake_season', models.JSONField(default=list, help_text="e.g. ['Winter (Oct)', 'Summer (Apr)']")),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='study_abroad.college')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='study_abroad.country')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=50)),
                ('target_degree', models.CharField(default='Masters', max_length=50)),
                ('preferred_field', models.CharField(default='Computer Science & AI', max_length=150)),
                ('cgpa', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('ielts_score', models.DecimalField(decimal_places=1, default=6.5, max_digits=3)),
                ('german_level', models.CharField(default='None', max_length=20)),
                ('budget_eur', models.IntegerField(default=12000)),
                ('resume_file_name', models.CharField(blank=True, max_length=255)),
                ('match_score', models.IntegerField(default=85)),
                ('is_college_revealed', models.BooleanField(default=False, help_text='Controls whether the student can see the specific College name or just the course/country.')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Matched', 'Matched'), ('Under Review', 'Under Review'), ('College Approved', 'College Approved'), ('Visa Processing', 'Visa Processing'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_abroad.college')),
                ('target_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_abroad.country')),
                ('matched_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_abroad.studyabroadcourse')),
            ],
        ),
    ]
