# Generated by Django 6.1 on 2026-09-11 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('Gift Package', 'Gift Package'), ('Tour Package', 'Tour Package (Europe / Goa Trip)'), ('Salary Incentive', 'Salary Incentive Bonus'), ('Course Subsidy', 'Course Subsidy Voucher'), ('Cashback', 'Direct Bank Cashback')], default='Gift Package', max_length=100)),
                ('points_cost', models.IntegerField(default=250)),
                ('monetary_value', models.CharField(default='₹25,000 Value', max_length=100)),
                ('badge', models.CharField(default='Popular', max_length=50)),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Limited Availability', 'Limited Availability'), ('On Request', 'On Request')], default='In Stock', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('tier_level', models.CharField(choices=[('Bronze Consultant', 'Bronze Consultant (5% Commission)'), ('Silver Ambassador', 'Silver Ambassador (10% Commission)'), ('Gold Strategic Partner', 'Gold Strategic Partner (15% Commission)'), ('Platinum Institutional Lead', 'Platinum Institutional Lead (20% Commission)')], default='Bronze Consultant', max_length=50)),
                ('referral_bonus_cash', models.CharField(default='₹3,000 / Referral', max_length=100)),
                ('points_per_referral', models.IntegerField(default=50)),
                ('milestone_threshold', models.IntegerField(default=5, help_text='Number of candidates to unlock tier')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardPromotionBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=255)),
                ('message_copy', models.TextField()),
                ('target_channels', models.JSONField(default=list, help_text="e.g. ['Meta Ads', 'LinkedIn', 'WhatsApp']")),
                ('sent_to_users_count', models.IntegerField(default=0)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Referral', 'Referral & Candidate Sourcing'), ('Course Milestone', 'Academic Milestone Completion'), ('Community', 'Community & Brand Promotion'), ('Institutional', 'College MoU / Institutional Tie-Up')], default='Referral', max_length=100)),
                ('points_reward', models.IntegerField(default=50)),
                ('cash_incentive', models.CharField(default='₹3,000 Payout', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=50)),
                ('points_spent', models.IntegerField()),
                ('payout_mode', models.CharField(default='Direct Bank Transfer (NEFT/IMPS)', max_length=100)),
                ('bank_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Approved by Marketing', 'Approved by Marketing'), ('Fulfilled / Disbursed', 'Fulfilled / Disbursed'), ('Rejected', 'Rejected')], default='Pending Review', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards_plan.rewardcatalogitem')),
            ],
        ),
    ]
