# Generated by Django 6.1 on 2026-09-11 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('target_country', models.CharField(default='Germany', max_length=100)),
                ('field', models.CharField(default='Software & IT', max_length=150)),
                ('years_of_experience', models.IntegerField(default=3)),
                ('highest_degree', models.CharField(default='B.Tech Computer Science', max_length=150)),
                ('primary_skills', models.JSONField(default=list, help_text='Parsed skill tokens')),
                ('german_level', models.CharField(default='None', max_length=20)),
                ('english_level', models.CharField(default='Fluent', max_length=50)),
                ('resume_file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Matched', 'Matched'), ('Interview Scheduled', 'Interview Scheduled'), ('Placed', 'Placed'), ('Archived', 'Archived')], default='New', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('Software & IT', 'Software & IT'), ('Healthcare', 'Healthcare'), ('Engineering', 'Engineering'), ('Business & Finance', 'Business & Finance'), ('Operations', 'Operations')], default='Software & IT', max_length=100)),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('city', models.CharField(default='Munich', max_length=100)),
                ('salary_range', models.CharField(default='€65,000 - €80,000 / yr', max_length=150)),
                ('contract_type', models.CharField(choices=[('Full-Time Permanent', 'Full-Time Permanent'), ('Dual Training (Ausbildung)', 'Dual Training (Ausbildung)'), ('Hybrid Contractor', 'Hybrid Contractor')], default='Full-Time Permanent', max_length=100)),
                ('blue_card_eligible', models.BooleanField(default=True)),
                ('required_skills', models.JSONField(default=list, help_text="e.g. ['Kubernetes', 'Go', 'AWS']")),
                ('min_experience', models.CharField(default='2+ Years', max_length=100)),
                ('min_german_level', models.CharField(choices=[('None', 'None'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='None', max_length=20)),
                ('openings', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Filled', 'Filled')], default='Active', max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(default='🏢', max_length=50)),
                ('industry', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('hiring_tier', models.CharField(choices=[('Strategic Partner', 'Strategic Partner'), ('Enterprise Client', 'Enterprise Client'), ('Direct Recruiter', 'Direct Recruiter')], default='Strategic Partner', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Audit', 'Under Audit')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=75)),
                ('matched_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Suggested', 'Suggested'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Offer Extended', 'Offer Extended'), ('Rejected', 'Rejected')], default='Suggested', max_length=50)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='job_search.candidateresume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='job_search.joblisting')),
            ],
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_search.partnercompany'),
        ),
    ]
